help:
	@echo "Usage: make [target]"
	@echo ""
	@echo "Targets:"
	@echo "  dev: Run the development server"
	@echo "  prod: Open the production site"


dev:
	pnpm run dev

prod:
	open https://zimmy.dev
